#!/usr/bin/env bash
if [[ ! -d /app/node_modules ]]; then
  echo "~> installing dependencies"
  if [ -f package-lock.json ]; then su node -c "npm ci"; 
    elif [ -f yarn.lock ]; then su node -c "yarn --frozen-lockfile"; 
    elif [ -f pnpm-lock.yaml ]; then su node -c "corepack enable pnpm && pnpm i --frozen-lockfile"; 
    else su node -c " pnpm i";
  fi
fi

echo "~> starting dev"
if [ -f package-lock.json ]; then su node -c "npm run start:dev"; 
  elif [ -f yarn.lock ]; then su node -c "yarn start:dev"; 
  elif [ -f pnpm-lock.yaml ]; then su node -c "pnpm start:dev"; 
  else echo "Lockfile not found." && exit 1; 
fi


